apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: nginx-cont
    image: nginx
    env:
      - name: course
        value: devops
      - name: student
        value: Pavan