apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: limits
    image: nginx
    env:
      - name: course
        value: devops
      - name: student
        value: Pavan
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        cpu: "30m"
        memory: "126Mi"