apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    app: expense
    project: exp-frontend
    module: frontend
    env: dev
  ports:
  - name: svc
    port: 80
    targetPort: 80